version: "2"
services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /project
    tty: true
volumes:
  database:
  