version: 1
formatters:
  simple:
    format: '%(asctime)s:%(name)s:%(levelname)s:%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    filename: 'logs/.log'
    formatter: simple
    backupCount: 7
    interval: 1
    when: "d"
loggers:
  nbot:
    level: DEBUG
  discord:
    level: DEBUG
root:
  level: INFO
  handlers: [console, file]